---
name: vhdl_ls
description: Fast VHDL language server and analysis library written in Rust.
homepage: https://github.com/VHDL-LS/rust_hdl
licenses:
  - Apache-2.0
languages:
  - VHDL
categories:
  - LSP

source:
  # renovate:datasource=github-tags
  id: pkg:github/VHDL-LS/rust_hdl@v0.64.0
  build:
    run: cargo build --release

bin:
  vhdl_ls: target/release
